title: "Dr. T L H"
description: "PhD Student in IS at the University"
url: "https://yoursite.com"
email: "your.email@university.edu"
orcid: "0000-0000-0000-0000"
twitter: "yourusername"
github: "yourusername"
linkedin: "yourname"

# Privacy settings
analytics:
  enabled: false
  provider: "plausible" # or "umami"
  domain: "yoursite.com"

# Site features
features:
  dark_mode: true
  search: true
  
# Navigation
navigation:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
  - name: "Publications"
    url: "/publications/"
  - name: "Teaching"
    url: "/teaching/"
  - name: "Blog"
    url: "/blog/"
  - name: "CV"
    url: "/cv/"
  - name: "Contact"
    url: "/contact/"